port: :8083
database_connection: "host={{DB_HOST}} port=5432 user={{DB_USER}} password={{DB_PASS}} dbname={{DB_NAME}} sslmode=disable"
rabbit_connection: "amqp://{{AMQP_USER}}:{{AMQP_PASS}}@{{AMQP_HOST}}:5672/"